# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Documents/Raven/version1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Documents/Raven/version1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Documents/Raven/version1/CMakeFiles /home/pi/Documents/Raven/version1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Documents/Raven/version1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RavenLib

# Build rule for target.
RavenLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RavenLib
.PHONY : RavenLib

# fast build rule for target.
RavenLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/build
.PHONY : RavenLib/fast

#=============================================================================
# Target rules for targets named Raven

# Build rule for target.
Raven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Raven
.PHONY : Raven

# fast build rule for target.
Raven/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Raven.dir/build.make CMakeFiles/Raven.dir/build
.PHONY : Raven/fast

#=============================================================================
# Target rules for targets named TrainRaven

# Build rule for target.
TrainRaven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TrainRaven
.PHONY : TrainRaven

# fast build rule for target.
TrainRaven/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainRaven.dir/build.make CMakeFiles/TrainRaven.dir/build
.PHONY : TrainRaven/fast

#=============================================================================
# Target rules for targets named ReinforceRaven

# Build rule for target.
ReinforceRaven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ReinforceRaven
.PHONY : ReinforceRaven

# fast build rule for target.
ReinforceRaven/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ReinforceRaven.dir/build.make CMakeFiles/ReinforceRaven.dir/build
.PHONY : ReinforceRaven/fast

#=============================================================================
# Target rules for targets named Manual_training

# Build rule for target.
Manual_training: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Manual_training
.PHONY : Manual_training

# fast build rule for target.
Manual_training/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manual_training.dir/build.make CMakeFiles/Manual_training.dir/build
.PHONY : Manual_training/fast

facedetector.o: facedetector.cpp.o
.PHONY : facedetector.o

# target to build an object file
facedetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/facedetector.cpp.o
.PHONY : facedetector.cpp.o

facedetector.i: facedetector.cpp.i
.PHONY : facedetector.i

# target to preprocess a source file
facedetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/facedetector.cpp.i
.PHONY : facedetector.cpp.i

facedetector.s: facedetector.cpp.s
.PHONY : facedetector.s

# target to generate assembly for a file
facedetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/facedetector.cpp.s
.PHONY : facedetector.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Raven.dir/build.make CMakeFiles/Raven.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Raven.dir/build.make CMakeFiles/Raven.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Raven.dir/build.make CMakeFiles/Raven.dir/main.cpp.s
.PHONY : main.cpp.s

manual_training.o: manual_training.cpp.o
.PHONY : manual_training.o

# target to build an object file
manual_training.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manual_training.dir/build.make CMakeFiles/Manual_training.dir/manual_training.cpp.o
.PHONY : manual_training.cpp.o

manual_training.i: manual_training.cpp.i
.PHONY : manual_training.i

# target to preprocess a source file
manual_training.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manual_training.dir/build.make CMakeFiles/Manual_training.dir/manual_training.cpp.i
.PHONY : manual_training.cpp.i

manual_training.s: manual_training.cpp.s
.PHONY : manual_training.s

# target to generate assembly for a file
manual_training.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Manual_training.dir/build.make CMakeFiles/Manual_training.dir/manual_training.cpp.s
.PHONY : manual_training.cpp.s

reinforce_train_your_raven.o: reinforce_train_your_raven.cpp.o
.PHONY : reinforce_train_your_raven.o

# target to build an object file
reinforce_train_your_raven.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ReinforceRaven.dir/build.make CMakeFiles/ReinforceRaven.dir/reinforce_train_your_raven.cpp.o
.PHONY : reinforce_train_your_raven.cpp.o

reinforce_train_your_raven.i: reinforce_train_your_raven.cpp.i
.PHONY : reinforce_train_your_raven.i

# target to preprocess a source file
reinforce_train_your_raven.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ReinforceRaven.dir/build.make CMakeFiles/ReinforceRaven.dir/reinforce_train_your_raven.cpp.i
.PHONY : reinforce_train_your_raven.cpp.i

reinforce_train_your_raven.s: reinforce_train_your_raven.cpp.s
.PHONY : reinforce_train_your_raven.s

# target to generate assembly for a file
reinforce_train_your_raven.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ReinforceRaven.dir/build.make CMakeFiles/ReinforceRaven.dir/reinforce_train_your_raven.cpp.s
.PHONY : reinforce_train_your_raven.cpp.s

servos.o: servos.cpp.o
.PHONY : servos.o

# target to build an object file
servos.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/servos.cpp.o
.PHONY : servos.cpp.o

servos.i: servos.cpp.i
.PHONY : servos.i

# target to preprocess a source file
servos.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/servos.cpp.i
.PHONY : servos.cpp.i

servos.s: servos.cpp.s
.PHONY : servos.s

# target to generate assembly for a file
servos.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RavenLib.dir/build.make CMakeFiles/RavenLib.dir/servos.cpp.s
.PHONY : servos.cpp.s

train_your_raven.o: train_your_raven.cpp.o
.PHONY : train_your_raven.o

# target to build an object file
train_your_raven.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainRaven.dir/build.make CMakeFiles/TrainRaven.dir/train_your_raven.cpp.o
.PHONY : train_your_raven.cpp.o

train_your_raven.i: train_your_raven.cpp.i
.PHONY : train_your_raven.i

# target to preprocess a source file
train_your_raven.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainRaven.dir/build.make CMakeFiles/TrainRaven.dir/train_your_raven.cpp.i
.PHONY : train_your_raven.cpp.i

train_your_raven.s: train_your_raven.cpp.s
.PHONY : train_your_raven.s

# target to generate assembly for a file
train_your_raven.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrainRaven.dir/build.make CMakeFiles/TrainRaven.dir/train_your_raven.cpp.s
.PHONY : train_your_raven.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Manual_training"
	@echo "... Raven"
	@echo "... RavenLib"
	@echo "... ReinforceRaven"
	@echo "... TrainRaven"
	@echo "... facedetector.o"
	@echo "... facedetector.i"
	@echo "... facedetector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... manual_training.o"
	@echo "... manual_training.i"
	@echo "... manual_training.s"
	@echo "... reinforce_train_your_raven.o"
	@echo "... reinforce_train_your_raven.i"
	@echo "... reinforce_train_your_raven.s"
	@echo "... servos.o"
	@echo "... servos.i"
	@echo "... servos.s"
	@echo "... train_your_raven.o"
	@echo "... train_your_raven.i"
	@echo "... train_your_raven.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

